# config.yaml

random_state: 42
n_splits: 5
n_trials: 10
n_jobs: 8  # Number of CPUs to use
sample_size: 0.2
verbosity:
  optuna: warning  # Options: critical, error, warning, info, debug
  catboost: silent  # Options: silent, verbose
  general: info  # General logging for the script
output_paths:
  model_dir: "./models"
  log_dir: "./logs"
catboost_params:
  iterations: [100, 1000]
  depth: [3, 10]
  learning_rate: [0.001, 0.1]  # using standard float format
  l2_leaf_reg: [1e-05, 0.1] # using scientific notation
  border_count: [32, 255]
  random_strength: [0, 10]
  bagging_temperature: [0, 1]
  early_stopping_rounds: 50
